version: '2'

services:
    nginx:
        build: nginx
        ports:
            - 80:80
            - 8080:8080

    ow1:
        build: ow1

    ow2:
        build: ow2

    node-red:
        build: node-red
        environment:
            - USERNAME=${NODE_USERNAME}
            - PASSWORD=${NODE_PASSWORD}
