version: '2'

services:
    nginx:
        build: nginx
        ports:
            - 8080:8080

    ow1:
        build: ow

    ow2:
        build: ow

    node-red:
        build: resin-node-red
        ports:
            - 80:80
        environment:
            - USERNAME=${NODE_USERNAME}
            - PASSWORD=${NODE_PASSWORD}
